### ISSUE TITLE
Bug: can select both candidates for president and secretary

### ISSUE THREAD

**Issue by AritroSaha10** [Fraser-Votes/client#34]
Not sure if you're supposed to be able to vote for two people for president & secretary, but I'll send it here:

### How to replicate
1. Go to voting ballot
2. Go to either the president slot or treasurer spot
3. Select one of the candidates 
4. Select the other
5. Select the candidate you originally picked

![demonstration](https://user-images.githubusercontent.com/29025984/121690189-87116700-ca93-11eb-95e9-bc5c783df1df.gif)

Something like this shows up. I didn't discover this, one of my classmates did. Not sure if it works after you submit, however a few of my classmates did say that it showed that they did vote for both.

**Comment by err53** [comment]
Yes, this is an intentional feature that was requested by school admin. We
probably should have made it more obvious...

**Comment by AritroSaha10** [comment]
Oh, my bad, I'll close the issue then
