### ISSUE TITLE
New vote does not overwrite old vote

### ISSUE THREAD

**Issue by RyanL123** [Fraser-Votes/client#8]
Right now the current vote needs to be unchecked to vote for another candidate in the same category instead of being able to overwrite the current vote by selecting a new candidate.

**Comment by davidli3100** [comment]
This will be added to release 0.7.0 as a hotfix.

Current priorities are mainly centered around the admin interface and service redundancy

**Comment by davidli3100** [comment]
fixed in d2e3294
